# Flutter profile configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/invest-platform
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/invest-platform/protocol/openid-connect/certs

# ? Garder uniquement cette ligne
server.tomcat.allow-encoded-slash=true

konnect.subscription.success.link=investplatform://payment-success
konnect.subscription.fail.link=investplatform://payment-failed